---
name: Run Tests
on:
  push:
    branches:
#     - '**'  alternative run on all branches
      - feature/github-actions
      - main
  pull_request:
    branches:
      - feature/github-actions
      - main

jobs:
  test:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        os: [ubuntu-latest]
#        node-version: [22, 24, 25]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
#          node-version: ${{ matrix.node-version }}
          node-version: '20'
          cache: 'npm'
      - run: npm ci --include=dev
      - run: npm test

